import serial, time

import matplotlib.pyplot as plt
import numpy as np


arduino = serial.Serial(port='COM4', baudrate=9600, bytesize=8)

numeros=[ 512 ,576 ,639 ,700 ,758, 812 ,862, 906, 943, 974 ,998 ,1014 , 
         1022  ,1022 , 1014 , 998 ,974, 943 ,906 ,862 ,812 ,758 ,700, 
         639, 576 ,512 ,448 ,385 ,324 ,266, 212, 162, 118 ,81 , 50 , 26 , 
         10 , 2 ,2, 10 , 26 , 50 , 81 , 118, 162, 212, 266, 324, 385, 448,512 ,
         576 ,639 ,700 ,758, 812 ,862, 906, 943, 974 ,998 ,1014 , 
         1022  ,1022 , 1014 , 998 ,974, 943 ,906 ,862 ,812 ,758 ,700, 
         639, 576 ,512,448 ,385 ,324 ,266, 212, 162, 118 ,81 , 50 , 26 , 
         10 , 2 ,2, 10 , 26 , 50 , 81 , 118, 162, 212, 266, 324, 385, 448]



listaenvio=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,
         25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,
         46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,
         67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,
         88,89,90,91,92,93,94,95,96,97,98,99,100,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,
         25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,
         46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,
         67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,
         88,89,90,91,92,93,94,95,96,97,98,99,100,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,
         25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,
         46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,
         67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,
         88,89,90,91,92,93,94,95,96,97,98,99,100,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,
         25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,
         46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,
         67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,
         88,89,90,91,92,93,94,95,96,97,98,99,100,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,
         25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,
         46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,
         67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,
         88,89,90,91,92,93,94,95,96,97,98,99,100]

i=0
j=0


while(i<=99):

    b=numeros[j]
    
    if(b/10000 >=1):
        a=int(b/10000)
        c=a%10
        listaenvio[i]=c
    else: 
        listaenvio[i]=0
    
    if(b/1000 >=1):
        a=int(b/1000)
        c=a%10
        listaenvio[i+1]=c
    else: 
        listaenvio[i+1]=0
        
    
    if(b/100 >=1):
        a=int(b/100)
        c=a%10
        listaenvio[i+2]=c
    else: 
        listaenvio[i+2]=0
   
  
    if(b/10 >=1):
        a=int(b/10)
        c=a%10
        listaenvio[i+3]=c
    else: 
        listaenvio[i+3]=0
        
    c=b%10
    listaenvio[i+4]=c
    i=i+5
    j=j+1
    


a=listaenvio[1]

# iniciar

time.sleep(2)
arduino.write(b'#')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'1')
time.sleep(2)
rawString = arduino.readline()
print(rawString)

#enviando los datos
time.sleep(2)
arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'5')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'1')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'2')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)



# numero 2

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'5')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'7')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'6')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

# numero 3

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'6')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'3')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'9')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

# numero 4

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'7')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 5

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'7')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'5')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'8')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 6

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'8')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'1')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'2')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)


#numero 7

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'8')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'6')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'2')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 8

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'9')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'6')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 9

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'9')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'4')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'3')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 10

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'9')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'7')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'4')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)


#numero 11

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'9')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'9')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'8')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 12

arduino.write(b'1')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'1')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'4')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 13

arduino.write(b'1')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'2')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'2')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 14

arduino.write(b'1')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'2')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'2')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 15

arduino.write(b'1')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'1')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'4')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 16

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'9')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'9')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'8')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 17

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'9')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'7')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'4')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 18

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'9')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'4')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'3')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 19

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'9')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'6')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 20

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'8')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'6')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'2')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 21

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'8')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'1')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'2')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 22

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'7')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'5')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'8')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 23

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'7')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 24

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'6')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'3')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'9')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 25

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'5')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'7')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'6')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 26

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'5')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'1')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'2')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 27

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'4')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'4')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'8')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 28

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'3')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'8')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'5')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 29

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'3')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'2')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'4')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 30

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'2')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'6')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'6')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 31

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'2')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'1')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'2')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 32

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'1')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'6')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'2')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 33

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'1')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'1')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'8')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 34

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'8')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'1')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)


#numero 35

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'5')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 36

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'2')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'6')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 37

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'1')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 38

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'2')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 39

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'2')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 40

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'1')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 41

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'2')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'6')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 42

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'5')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 43

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'8')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'1')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 44

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'1')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'1')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'8')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 45

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'1')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'6')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'2')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 46

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'2')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'1')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'2')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 47

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'2')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'6')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'6')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 48

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'3')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'2')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'4')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 49

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'3')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'8')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'5')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 50

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'4')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'4')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'8')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 51

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'5')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'1')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'2')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 52

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'5')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'7')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'6')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 53

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'6')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'3')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'9')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 54

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'7')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 55

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'7')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'5')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'8')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 56

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'8')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'1')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'2')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 57

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'8')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'6')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'2')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 58

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'9')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'6')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 59

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'9')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'4')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'3')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 60

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'9')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'7')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'4')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 61

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'9')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'9')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'8')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 62

arduino.write(b'1')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'1')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'4')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 63

arduino.write(b'1')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'2')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'2')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 64

arduino.write(b'1')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'2')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'2')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 65

arduino.write(b'1')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'1')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'4')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 66

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'9')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'9')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'8')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 67

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'9')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'7')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'4')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 68

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'9')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'4')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'3')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 69

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'9')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'6')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 70

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'8')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'6')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'2')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 71

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'8')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'1')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'2')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 72

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'7')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'5')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'8')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 73

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'7')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 74

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'6')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'3')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'9')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 75

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'5')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'7')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'6')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 76

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'5')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'1')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'2')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 77

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'4')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'4')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'8')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 78

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'3')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'8')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'5')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 79

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'3')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'2')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'4')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

#numero 80

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'2')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'6')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'6')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)



#numero 81

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'2')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'1')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'2')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)



#numero 82

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'1')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'6')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'2')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)


#numero 83

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'1')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'1')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'8')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)



#numero 84

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'8')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'1')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)




#numero 85

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'5')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)



#numero 86

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'2')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'6')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)


#numero 87

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'1')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)


#numero 88

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'2')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)



#numero 89

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'2')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)


#numero 90

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'1')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)



#numero 91

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'2')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'6')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)


#numero 92

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'5')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)



#numero 93

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'8')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'1')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)



#numero 94

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'1')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'1')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'8')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)


#numero 95

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'1')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'6')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'2')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)



#numero 96

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'2')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'1')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'2')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)



#numero 97

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'2')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'6')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'6')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)



#numero 98

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'3')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'2')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'4')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)



#numero 99

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'3')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'8')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'5')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)



#numero 100

arduino.write(b'0')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'4')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)

arduino.write(b'4')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
arduino.write(b'8')
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)
rawString = arduino.readline()
print(rawString)
time.sleep(2)


plt.plot(numeros)
# Show the plot
plt.show()

arduino.close()



    